### ISSUE TITLE
Have the decision process function be async

### ISSUE THREAD

**Issue by aurelien-clu** [disintegrate-es/disintegrate#123]
Would it be possible to have the `Decision` `fn process(...)` be asynchronous?

I feel like many things currently already are asynchronous so this could be as well. (perhaps other functions as well?)

I came across the need to make async io calls during a decision, I managed to work around that so I don't have a strong need at the moment for this change but I am wondering whether it makes sense (unless by design this should be avoided?) and also if it could be useful to others.

E.g. if one need to target a remote services with an http call during a decision.

I do understand that this could be a complex or time consuming change, so I would understand if you would rather not spend time for this considering that there may be only a small need. 😉 

In any case, thank you for your `disintegrate` 😄

**Comment by valerio-iachini** [comment]
Hi @aurelien-clu,

Thanks for raising the question!

Could you share more about your use case? This would help us determine if async support is needed.

We could make the process function async, but we've avoided it so far to encourage the following practices, even though you can technically use blocking code within the function:
1. Fetching data from external services: It’s usually better to fetch the data before executing the decision. This keeps decisions short and avoids conflicts when storing the result.
2. External calls with side effects: If the call modifies or creates resources, it’s better to handle it after the decision. For example, the decision can emit an event saying a request that respects the business invariants has been received. An event listener can then make the call, and another command can save the result. This improves consistency, simplifies retry logic, and helps with long-running processes. 

The goal is to keep decisions simple and focused on evaluating business rules and updating the state.

**Comment by aurelien-clu** [comment]
My use case would be to process untrusted data (<5 MB) by an external lambda.

I would have:

- API async server with disintegrate & secrets (e.g. database access)
- lambda without any secrets

An API client would send a file to the API server, the server would within a decision call the lambda to parse & process the raw bytes and return trusted data or fail.

So in my use case, I can definitely do this before the disintegrate decision.

I understand your goal to keep it simple.

I don't think I will get a strong need for this in the feature but if I do, I will make sure to share with you the use case for it. 😉
