### ISSUE TITLE
[Question] How to Disable DDL Queries During PostgreSQL Event Store Initialization in Restricted Environments?

### ISSUE THREAD

**Issue by gmkumar2005** [disintegrate-es/disintegrate#138]
Disintegrate uses a PostgreSQL event store and initializes by running DDL queries (via SQLx) to create tables like `event` and `event_sequence`. These scripts can be moved to SQLx migrations, including the domain_identifier_columns.

However, in some environments, database admins do not allow running DDL queries. Is there a way to skip these queries during initialization?

**Comment by luca-iachini** [comment]
Hi @gmkumar2005,
Thanks for the feedback! 
At the moment, it is not possible. We'll add this feature in the next release of the library.
